version: "3.4"

services:
  back:
    working_dir: /app
    image: ghcr.io/step3003/php-fpm-alpine:4.1.0
    env_file: ./.env
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: "1"
    ports:
      - 80:8000
    # Первый можно использовать любой незанятый.
    command: php artisan serve --host 0.0.0.0
    volumes:
      - ./:/app:cached

  db:
    restart: "always"
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # Если не нужны порты наружу и/или заняты, можно закомментировать.
